# ============================================================
#
#   ██████╗ ██╗  ██╗███████╗██╗  ██╗ ██████╗ ██╗   ██╗██████╗
#   ██╔══██╗██║  ██║██╔════╝██║  ██║██╔═══██╗██║   ██║██╔══██╗
#   ██████╔╝███████║███████╗███████║██║   ██║██║   ██║██████╔╝
#   ██╔══██╗██╔══██║╚════██║██╔══██║██║   ██║╚██╗ ██╔╝██╔══██╗
#   ██║  ██║██║  ██║███████║██║  ██║╚██████╔╝ ╚████╔╝ ██║  ██║
#   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝   ╚═══╝  ╚═╝  ╚═╝
#
#   Office Suite Universal Installer
#   Author  : rhshourav
#   GitHub  : https://github.com/rhshourav/Windows-Scripts
#   Version : 3.3.0  |  Windows 10 / 11  |  x64
#
#   USAGE (run as Administrator):
#     iex (irm "https://raw.githubusercontent.com/rhshourav/Windows-Scripts/main/Install-Office.ps1")
#
# ============================================================

$ErrorActionPreference = "SilentlyContinue"
Set-StrictMode -Off

# ================================================================
#  CONSTANTS
# ================================================================
$SCRIPT_VER  = "3.3.0"
$SCRIPT_AUTH = "rhshourav"
$SCRIPT_REPO = "https://github.com/rhshourav/Windows-Scripts"
$CON_W       = 78   # max line width — NEVER exceed or \r breaks

# ================================================================
#  PACKAGE DEFINITIONS
#
#  XML is generated by this script — NOT taken from the ZIP.
#  This avoids exit code 17002 (PRODUCT_NOT_APPLICABLE) caused
#  by wrong channel/ProductID in bundled XMLs.
#
#  ZipUrl is only used to get setup.exe (Microsoft's ODT binary).
# ================================================================
$PACKAGES = @(
    [ordered]@{
        Id        = 1
        Name      = "Microsoft 365 (Office 365)"
        Short     = "M365"
        ZipUrl    = "https://raw.githubusercontent.com/rhshourav/ideal-fishstick/refs/heads/main/O365.zip"
        ZipName   = "O365.zip"
        # Generated XML — Channel=Current, O365ProPlusRetail (works on any Windows 10/11)
        ConfigXml = @"
<Configuration>
  <Add OfficeClientEdition="64" Channel="Current" MigrateArch="TRUE">
    <Product ID="O365ProPlusRetail">
      <Language ID="MatchOS" />
      <ExcludeApp ID="Groove" />
      <ExcludeApp ID="Lync"  />
    </Product>
  </Add>
  <Updates Enabled="TRUE" />
  <Display Level="None" AcceptEULA="TRUE" />
  <Property Name="FORCEAPPSHUTDOWN" Value="TRUE" />
</Configuration>
"@
    },
    [ordered]@{
        Id        = 2
        Name      = "Office LTSC 2021"
        Short     = "LTSC2021"
        ZipUrl    = "https://raw.githubusercontent.com/rhshourav/ideal-fishstick/refs/heads/main/OLTSC-2021.zip"
        ZipName   = "OLTSC-2021.zip"
        ConfigXml = @"
<Configuration>
  <Add OfficeClientEdition="64" Channel="PerpetualVL2021">
    <Product ID="ProPlus2021Volume">
      <Language ID="en-us" />
      <ExcludeApp ID="Teams" />
    </Product>
  </Add>
  <Updates Enabled="FALSE" />
  <Display Level="None" AcceptEULA="TRUE" />
  <Property Name="FORCEAPPSHUTDOWN" Value="TRUE" />
</Configuration>
"@
    },
    [ordered]@{
        Id        = 3
        Name      = "Office LTSC 2024"
        Short     = "LTSC2024"
        ZipUrl    = "https://raw.githubusercontent.com/rhshourav/ideal-fishstick/refs/heads/main/OLTSC-2024.zip"
        ZipName   = "OLTSC-2024.zip"
        ConfigXml = @"
<Configuration>
  <Add OfficeClientEdition="64" Channel="PerpetualVL2024">
    <Product ID="ProPlus2024Volume">
      <Language ID="en-us" />
    </Product>
  </Add>
  <Updates Enabled="FALSE" />
  <Display Level="None" AcceptEULA="TRUE" />
  <Property Name="FORCEAPPSHUTDOWN" Value="TRUE" />
</Configuration>
"@
    },
    [ordered]@{
        Id        = 4
        Name      = "Office 2019"
        Short     = "O2019"
        ZipUrl    = "https://raw.githubusercontent.com/rhshourav/ideal-fishstick/refs/heads/main/O2019.zip"
        ZipName   = "O2019.zip"
        ConfigXml = @"
<Configuration>
  <Add OfficeClientEdition="64" Channel="PerpetualVL2019">
    <Product ID="ProPlus2019Volume">
      <Language ID="en-us" />
    </Product>
  </Add>
  <Updates Enabled="FALSE" />
  <Display Level="None" AcceptEULA="TRUE" />
  <Property Name="FORCEAPPSHUTDOWN" Value="TRUE" />
</Configuration>
"@
    }
)

# ================================================================
#  THEME / OUTPUT HELPERS
# ================================================================
function Set-Theme {
    try {
        $h = $Host.UI.RawUI
        $h.BackgroundColor = 'Black'
        $h.ForegroundColor = 'White'
        $w = $h.WindowSize
        if ($w.Width -lt ($CON_W + 4)) { $w.Width = $CON_W + 4; $h.WindowSize = $w }
    } catch {}
    Clear-Host
}

function Write-C {
    param([string]$msg, [string]$col = 'White', [switch]$NoNewLine)
    if ($NoNewLine) { Write-Host $msg -ForegroundColor $col -NoNewline }
    else            { Write-Host $msg -ForegroundColor $col }
}
function Write-Div  { param([string]$c='-',[string]$col='DarkGray'); Write-C ($c * $CON_W) $col }
function Write-Step { param([string]$m); Write-C "  [>>] $m" 'Yellow'  }
function Write-OK   { param([string]$m); Write-C "  [OK] $m" 'Green'   }
function Write-Warn { param([string]$m); Write-C "  [!!] $m" 'Yellow'  }
function Write-Fail { param([string]$m); Write-C "  [XX] $m" 'Red'     }
function Write-Info { param([string]$m); Write-C "       $m" 'DarkGray'}

# ================================================================
#  PROGRESS BAR
#
#  All output lines are padded to exactly ($CON_W-1) chars before
#  being printed with \r.  This guarantees:
#    - No line wrap (which breaks \r-based overwriting)
#    - No leftover chars from a longer previous line
#
#  $Pct  0-100  = deterministic filled bar
#  $Pct  -1     = bouncing indeterminate block
# ================================================================
$script:Tick = 0

function Show-Bar {
    param([string]$Label, [int]$Pct, [string]$Info = '')

    $script:Tick++
    $BAR_W = 32   # inner bar width (short = safe on narrow terminals)

    $lbl = $Label.PadRight(18)
    if ($lbl.Length -gt 18) { $lbl = $lbl.Substring(0,18) }

    if ($Pct -lt 0) {
        $range = $BAR_W - 3
        # Bounce: 0..range..0
        $raw   = $script:Tick % ($range * 2)
        $pos   = if ($raw -le $range) { $raw } else { ($range * 2) - $raw }
        $inner = (' ' * $pos) + '[=]' + (' ' * ($range - $pos))
        $bar   = '|' + $inner + '|'
        $right = "  $Info"
    } else {
        $f     = [int][Math]::Round($Pct / 100 * $BAR_W)
        $e     = $BAR_W - $f
        $bar   = '|' + ([string][char]9608 * $f) + ([string][char]9617 * $e) + '|'
        $right = "  $Pct%  $Info"
    }

    $raw   = "  $lbl $bar$right"
    $maxL  = $CON_W - 1
    if ($raw.Length -gt $maxL) { $raw = $raw.Substring(0, $maxL) }
    $raw   = $raw.PadRight($maxL)

    Write-Host "`r$raw" -NoNewline -ForegroundColor Cyan
}

function Clear-Bar {
    Write-Host ("`r" + (' ' * ($CON_W - 1)) + "`r") -NoNewline
}

# ================================================================
#  BANNER
# ================================================================
function Write-Banner {
    Clear-Host
    Write-C ""
    Write-C "  ██████╗ ██╗  ██╗███████╗██╗  ██╗ ██████╗ ██╗   ██╗██████╗  " 'Cyan'
    Write-C "  ██╔══██╗██║  ██║██╔════╝██║  ██║██╔═══██╗██║   ██║██╔══██╗ " 'Cyan'
    Write-C "  ██████╔╝███████║███████╗███████║██║   ██║██║   ██║██████╔╝  " 'Cyan'
    Write-C "  ██╔══██╗██╔══██║╚════██║██╔══██║██║   ██║╚██╗ ██╔╝██╔══██╗  " 'Cyan'
    Write-C "  ██║  ██║██║  ██║███████║██║  ██║╚██████╔╝ ╚████╔╝ ██║  ██║  " 'Cyan'
    Write-C "  ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝   ╚═══╝  ╚═╝  ╚═╝  " 'Cyan'
    Write-C ""
    Write-Div '=' 'DarkCyan'
    Write-C "  Office Suite Universal Installer  |  v$SCRIPT_VER  |  $SCRIPT_AUTH" 'DarkCyan'
    Write-Div '=' 'DarkCyan'
    Write-C ""
}

# ================================================================
#  ADMIN CHECK
# ================================================================
function Assert-Admin {
    $ok = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
          ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
    if (-not $ok) {
        Write-Fail "Must be run as Administrator."
        Write-Info "Right-click PowerShell -> Run as administrator"
        Write-C ""; Read-Host "  Press ENTER to exit"; exit 1
    }
}

function Enable-Tls {
    try { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 } catch {}
}

# ================================================================
#  TELEMETRY
# ================================================================
function Send-Telemetry { param($pkg)
    try {
        $ips = (Get-CimInstance Win32_NetworkAdapterConfiguration -Filter 'IPEnabled=True' -EA SilentlyContinue |
                ForEach-Object { $_.IPAddress } |
                Where-Object   { $_ -match '^\d{1,3}(\.\d{1,3}){3}$' } |
                Select-Object -Unique) -join ', '
        $body = ([ordered]@{
            token = 'shourav'
            text  = "Office Installer v$SCRIPT_VER | $($pkg.Short)`nUser:$env:USERNAME PC:$env:COMPUTERNAME IP:$ips"
        } | ConvertTo-Json)
        Invoke-RestMethod -Uri 'https://cryocore.rhshourav.workers.dev/message' `
            -Method Post -ContentType 'application/json' `
            -Body $body -TimeoutSec 5 -EA SilentlyContinue | Out-Null
    } catch {}
}

# ================================================================
#  DOWNLOAD — BITS (real %) with IWR fallback
#  No WebClient async: avoids closure scope bugs entirely
# ================================================================
function Get-FileProgress {
    param([string]$Url, [string]$Dest, [string]$Label)

    try {
        Import-Module BitsTransfer -EA Stop
        $job = Start-BitsTransfer -Source $Url -Destination $Dest -Asynchronous -EA Stop

        while ($job.JobState -notin @('Transferred','Error','TransientError')) {
            $tot  = $job.BytesTotal
            $recv = $job.BytesTransferred
            if ($tot -gt 0) {
                Show-Bar $Label ([int]($recv / $tot * 100)) ("{0:N1}/{1:N1} MB" -f ($recv/1MB),($tot/1MB))
            } else {
                Show-Bar $Label -1 "connecting..."
            }
            Start-Sleep -Milliseconds 300
        }

        if ($job.JobState -eq 'Transferred') {
            Complete-BitsTransfer -BitsJob $job -EA SilentlyContinue
            Clear-Bar; return
        }
        Remove-BitsTransfer -BitsJob $job -EA SilentlyContinue
    } catch {}

    # Fallback: synchronous IWR — no live %, but always works
    Show-Bar $Label -1 "downloading..."
    try {
        Invoke-WebRequest -Uri $Url -OutFile $Dest -UseBasicParsing -EA Stop
    } catch {
        Clear-Bar; throw "Download failed: $_"
    }
    Clear-Bar
}

# ================================================================
#  WAIT FOR A PROCESS + ALL ITS NAMED CHILD PROCESSES
#
#  ODT /configure starts setup.exe, which spawns OfficeC2RClient.exe
#  (the actual installer). If we only wait for setup.exe we return
#  while installation is still running in the background.
#
#  Strategy:
#    1. Wait for the direct process ($Proc) to exit.
#    2. Then wait for any OfficeC2RClient / OfficeClickToRun children
#       to also finish — these are the real installers.
#    3. Time-box the child wait at 45 minutes to avoid infinite hang.
# ================================================================
function Wait-OdtComplete {
    param([System.Diagnostics.Process]$Proc, [string]$WorkDir, [string]$Label)

    $officeDir = Join-Path $WorkDir "Office"
    $spinChars = '|/-\'
    $tick      = 0
    $lastMB    = 0
    $stuckFor  = 0

    # ---- Phase A: wait for setup.exe /configure ----
    do {
        try { $Proc.Refresh() } catch {}
        $tick++

        # Measure Office folder size growth as download proxy
        $sizeMB = 0
        if (Test-Path $officeDir) {
            try {
                $sizeMB = [int](
                    (Get-ChildItem $officeDir -Recurse -File -EA SilentlyContinue |
                     Measure-Object -Property Length -Sum -EA SilentlyContinue).Sum / 1MB
                )
            } catch {}
        }

        if ($sizeMB -ne $lastMB) { $stuckFor = 0; $lastMB = $sizeMB } else { $stuckFor++ }

        $spin = $spinChars[$tick % 4]
        # Rough target: ~2000 MB for M365, cap at 98% while running
        $pct  = [Math]::Min(98, [int]($sizeMB / 2000 * 100))

        if ($stuckFor -gt 15) {
            Show-Bar $Label -1 "$spin installing..."
        } else {
            Show-Bar $Label $pct "$spin ${sizeMB} MB"
        }

        Start-Sleep -Seconds 3

    } while (-not $Proc.HasExited)

    # ---- Phase B: wait for OfficeC2RClient / OfficeClickToRun children ----
    # These processes do the actual disk write after setup.exe exits.
    $childNames  = @('OfficeC2RClient','OfficeClickToRun','setup')
    $deadlineMin = 45
    $waited      = 0

    do {
        $children = @(Get-Process -Name $childNames -EA SilentlyContinue |
                      Where-Object { -not $_.HasExited })

        if ($children.Count -eq 0) { break }

        $waited++
        if ($waited -gt ($deadlineMin * 4)) {   # 4 checks/min (every 15s)
            Write-C ""
            Write-Warn "Timed out waiting for Office background processes. Install may still be running."
            break
        }

        $tick++
        $spin = $spinChars[$tick % 4]
        Show-Bar $Label -1 "$spin finalizing... (${waited}s)"
        Start-Sleep -Seconds 15

    } while ($true)

    Clear-Bar
}

# ================================================================
#  WATCH ODT /download (manifests — fast phase)
# ================================================================
function Watch-OdtDownload {
    param([System.Diagnostics.Process]$Proc, [string]$OfficeDir, [string]$Label)

    $lastCount = 0
    do {
        try { $Proc.Refresh() } catch {}
        $count = 0
        if (Test-Path $OfficeDir) {
            $count = @(Get-ChildItem $OfficeDir -Recurse -File -EA SilentlyContinue).Count
        }
        $lastCount = $count
        Show-Bar $Label ([Math]::Min(99, $count * 8)) "$count files"
        Start-Sleep -Seconds 2
    } while (-not $Proc.HasExited)
    Clear-Bar
}

# ================================================================
#  VERIFY
# ================================================================
function Test-OfficePresent {
    $paths = @(
        "$env:ProgramFiles\Microsoft Office\Office16\WINWORD.EXE",
        "${env:ProgramFiles(x86)}\Microsoft Office\Office16\WINWORD.EXE"
    )
    foreach ($p in $paths) { if (Test-Path $p) { return $true } }
    return $false
}

# ================================================================
#  INSTALL ONE PACKAGE
# ================================================================
function Install-Package { param($pkg)

    $uid     = ([Guid]::NewGuid().ToString('N')).Substring(0,6)
    $workDir = Join-Path $env:TEMP "OfficeInstall_$($pkg.Short)_$uid"
    $zipPath = Join-Path $workDir $pkg.ZipName
    $xmlPath = Join-Path $workDir "Install_$($pkg.Short).xml"

    Write-C ""
    Write-Div '-' 'DarkCyan'
    Write-C "  Package  : $($pkg.Name)" 'Cyan'
    Write-C "  WorkDir  : $workDir" 'DarkGray'
    Write-Div '-' 'DarkCyan'
    Write-C ""

    Send-Telemetry $pkg

    $ok = $false
    try {

        # 1. Working directory
        New-Item -ItemType Directory -Path $workDir -Force -EA Stop | Out-Null
        Write-Step "Work directory created."

        # 2. Write our own XML (ignore whatever XML is in the ZIP)
        #    This is the fix for exit code 17002.
        Set-Content -LiteralPath $xmlPath -Value $pkg.ConfigXml -Encoding UTF8 -EA Stop
        Write-OK "Configuration XML written."
        Write-Info "Config : $xmlPath"

        # 3. Download ZIP (we only need setup.exe from it)
        Write-Step "Downloading ODT package..."
        Enable-Tls
        Get-FileProgress -Url $pkg.ZipUrl -Dest $zipPath -Label "Get ZIP"
        if (-not (Test-Path $zipPath)) { throw "ZIP missing after download. URL: $($pkg.ZipUrl)" }
        Write-OK ("Downloaded  ({0:N1} MB)" -f ((Get-Item $zipPath).Length / 1MB))

        # 4. Extract
        Write-Step "Extracting..."
        try { Expand-Archive -Path $zipPath -DestinationPath $workDir -Force -EA Stop }
        catch { throw "Extraction failed: $_" }
        Write-OK "Extracted."

        # 5. Locate setup.exe
        $setupExe = Get-ChildItem $workDir -Recurse -Filter 'setup.exe' -File -EA SilentlyContinue |
                    Select-Object -First 1
        if (-not $setupExe) { throw "setup.exe not found in ZIP." }
        Write-Info "Setup  : $($setupExe.FullName)"

        # ----------------------------------------------------------------
        # 6. ODT /download
        #    Downloads small manifest / CAB index files only (~8-20 files).
        #    Completes in seconds.  8 files = NORMAL / DONE.
        # ----------------------------------------------------------------
        Write-C ""
        Write-Step "Phase 1/2 — Fetching manifests..."
        Write-Info "Downloads index files only. Completes in seconds."
        Write-C ""

        $officeDir = Join-Path $workDir "Office"

        $dlProc = Start-Process `
            -FilePath         $setupExe.FullName `
            -ArgumentList     "/download `"$xmlPath`"" `
            -WorkingDirectory $workDir `
            -PassThru -EA Stop

        if ($null -eq $dlProc) { throw "Failed to launch ODT /download." }

        Watch-OdtDownload -Proc $dlProc -OfficeDir $officeDir -Label "Manifests"

        try { $dlProc.Refresh() } catch {}
        if ($dlProc.ExitCode -ne 0) {
            throw "ODT /download failed with exit code $($dlProc.ExitCode)."
        }
        Write-OK "Manifests ready."

        # ----------------------------------------------------------------
        # 7. ODT /configure
        #    Downloads 1-3 GB AND installs.  setup.exe may exit before
        #    OfficeC2RClient.exe finishes — we wait for both.
        # ----------------------------------------------------------------
        Write-C ""
        Write-Step "Phase 2/2 — Downloading + Installing Office..."
        Write-Info "Downloads 1-3 GB from Microsoft. May take 5-30 minutes."
        Write-Info "Do NOT close this window."
        Write-C ""

        $instProc = Start-Process `
            -FilePath         $setupExe.FullName `
            -ArgumentList     "/configure `"$xmlPath`"" `
            -WorkingDirectory $workDir `
            -PassThru -EA Stop

        if ($null -eq $instProc) { throw "Failed to launch ODT /configure." }

        Wait-OdtComplete -Proc $instProc -WorkDir $workDir -Label "Download+Install"

        try { $instProc.Refresh() } catch {}
        if ($instProc.ExitCode -notin @(0, $null)) {
            throw "ODT /configure failed. Exit code: $($instProc.ExitCode). Check: $env:TEMP\USL-*.log"
        }
        Write-OK "Installer finished."

        # 8. Verify
        if (Test-OfficePresent) {
            Write-OK "WINWORD.EXE confirmed on disk."
        } else {
            Write-Warn "WINWORD.EXE not found in default path."
            Write-Info "Office may still be finishing up. Launch Word in a minute to verify."
        }

        $ok = $true

    } catch {
        Write-C ""
        Write-Fail "Failed : $($pkg.Name)"
        Write-Fail "Reason : $_"
        Write-Warn "Skipping to next package."
    } finally {
        try {
            if (Test-Path $workDir) {
                Write-C ""; Write-Step "Cleaning up temp files..."
                Remove-Item -LiteralPath $workDir -Recurse -Force -EA SilentlyContinue
                Write-OK "Temp files removed."
            }
        } catch {}
    }

    return $ok
}

# ================================================================
#  MENU
# ================================================================
function Show-Menu {
    Write-C "  Available Packages" 'White'; Write-C ""
    foreach ($p in $PACKAGES) { Write-C ("  [{0}]  {1}" -f $p.Id, $p.Name) 'Yellow' }
    Write-C ""
    Write-C "  [A]  Install ALL packages" 'Green'
    Write-C "  [Q]  Quit" 'Red'
    Write-C ""; Write-Div '-' 'DarkGray'; Write-C ""
    Write-C "  Separate multiple choices with commas  (e.g.  1,2  or  A)" 'DarkGray'
    Write-C ""
    Write-C "  > " 'Cyan' -NoNewLine
}

function Resolve-Selection { param([string]$raw)
    $raw = $raw.Trim()
    if ($raw -match '^[Qq]$') { return 'QUIT' }
    if ($raw -match '^[Aa]$') { return $PACKAGES }
    $sel = [System.Collections.Generic.List[object]]::new()
    foreach ($tok in ($raw -split ',')) {
        $tok = $tok.Trim(); $id = 0
        if ([int]::TryParse($tok,[ref]$id)) {
            $m = $PACKAGES | Where-Object { $_.Id -eq $id }
            if ($m) { $sel.Add($m) } else { Write-Warn "Unknown option '$tok' — ignored." }
        }
    }
    return $sel
}

# ================================================================
#  ENTRY POINT
# ================================================================
Set-Theme
Assert-Admin
Enable-Tls
Write-Banner

Write-C "  Author   : $SCRIPT_AUTH" 'DarkGray'
Write-C "  Repo     : $SCRIPT_REPO" 'DarkGray'
Write-C "  Machine  : $env:COMPUTERNAME  |  User: $env:USERNAME" 'DarkGray'
Write-C ""; Write-Div '=' 'DarkCyan'; Write-C ""

Show-Menu
$raw = Read-Host

$sel = Resolve-Selection $raw
if ($sel -eq 'QUIT') { Write-C ""; Write-C "  Aborted." 'Yellow'; Write-C ""; exit 0 }

$queue = @($sel)
if ($queue.Count -eq 0) { Write-C ""; Write-Warn "Nothing selected."; Write-C ""; exit 0 }

Write-C ""; Write-Div '-' 'DarkCyan'
Write-C "  Queued for installation:" 'White'; Write-C ""
foreach ($p in $queue) { Write-C "    +  $($p.Name)" 'Cyan' }
Write-C ""
Write-C "  Proceed? [Y/N] > " 'White' -NoNewLine
$confirm = (Read-Host).Trim()
if ($confirm -notmatch '^[Yy]$') { Write-C ""; Write-C "  Cancelled." 'Yellow'; Write-C ""; exit 0 }

$results = [ordered]@{}
foreach ($pkg in $queue) {
    $results[$pkg.Name] = (Install-Package $pkg)
}

Write-C ""; Write-Div '=' 'DarkCyan'
Write-C "  SUMMARY" 'White'; Write-C ""
foreach ($name in $results.Keys) {
    if ($results[$name]) { Write-C "  [OK]  $name" 'Green' }
    else                 { Write-C "  [XX]  $name  -- see errors above" 'Red' }
}
Write-C ""
Write-C "  Logs : $env:TEMP\USL-*.log" 'DarkGray'
Write-C "  Next : Launch Word or Excel to verify activation." 'DarkGray'
Write-Div '=' 'DarkCyan'; Write-C ""

# SIG # Begin signature block
# MIIb1AYJKoZIhvcNAQcCoIIbxTCCG8ECAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUpqrSOepAAUiszkDZot1MG/l3
# 8d2gghZEMIIDBjCCAe6gAwIBAgIQEL8pRoGkFYRO4LQqey1D4DANBgkqhkiG9w0B
# AQsFADAbMRkwFwYDVQQDDBBSSFNIT1VSQVYtSVQtT3BzMB4XDTI2MDcwNzA4MDE1
# N1oXDTI5MDcwNzA4MTE1N1owGzEZMBcGA1UEAwwQUkhTSE9VUkFWLUlULU9wczCC
# ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALFj11KDAqN3fhbDT9fvgrLF
# VemPYmcud3qA+9Sc4RojOjElODGXyaOlBSVmDGpmCkNRC+dnkGCLB8bYb3gsnHey
# Ud99DA8tvkTgb06+B1pigTZUmhyAwyPiu77+h224c8SsZFkmgQ/Dh2Sc2ynNocZe
# 773d6a/B4DRg7/K9xV8jFap6BP1fjaM3Do40GSL+OVnXl2ssvfFk4FyP5fc8Czz5
# MJ5IJKRFrnHv3kNcmyz5mnz0LoBQs/JtHpWg3BogIalJ2tyCiZgk0xIsz5j5UjhA
# /KepfnWGpCowJ/NJWnmOZcikFlDPggI27QNc/IbxZ035ht+Zgc7b1Cf68GmL/8UC
# AwEAAaNGMEQwDgYDVR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoGCCsGAQUFBwMDMB0G
# A1UdDgQWBBRJ+13W7/PcqVgZXZf87/JdXvGqxjANBgkqhkiG9w0BAQsFAAOCAQEA
# MDUJsw0AephOCByoLTFSm8hnB4I7s8ddA64vDTv4QF2TcXdrd/glByhEQexUEDpw
# lPCSbzHAmRM5X71QYNoB/CDlCoAO8BQnbegqkhAx8ubRyciwsLA4ZPp+/GFbgZaV
# khkOWpL6v6fmU3kSB5px+roqOuMjmqvbtCDlC4JH25WuDEgGJQhqpgdQSZdomWjH
# le/GnQKt4Y18ysVFvgE1lRO8x6gkJ5IJbZPJ0Q//2xCvtM0WpjXmQl1RHV/7tqDS
# fqprCQxuKiTPC64VfafzeS7IUNJMgQS73H6wuaKdeT85PIxreleNwNXfbr4O/FY3
# eqlSEZAqzKtZXfNFWPmHazCCBY0wggR1oAMCAQICEA6bGI750C3n79tQ4ghAGFow
# DQYJKoZIhvcNAQEMBQAwZTELMAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0
# IEluYzEZMBcGA1UECxMQd3d3LmRpZ2ljZXJ0LmNvbTEkMCIGA1UEAxMbRGlnaUNl
# cnQgQXNzdXJlZCBJRCBSb290IENBMB4XDTIyMDgwMTAwMDAwMFoXDTMxMTEwOTIz
# NTk1OVowYjELMAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcG
# A1UECxMQd3d3LmRpZ2ljZXJ0LmNvbTEhMB8GA1UEAxMYRGlnaUNlcnQgVHJ1c3Rl
# ZCBSb290IEc0MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAv+aQc2je
# u+RdSjwwIjBpM+zCpyUuySE98orYWcLhKac9WKt2ms2uexuEDcQwH/MbpDgW61bG
# l20dq7J58soR0uRf1gU8Ug9SH8aeFaV+vp+pVxZZVXKvaJNwwrK6dZlqczKU0RBE
# EC7fgvMHhOZ0O21x4i0MG+4g1ckgHWMpLc7sXk7Ik/ghYZs06wXGXuxbGrzryc/N
# rDRAX7F6Zu53yEioZldXn1RYjgwrt0+nMNlW7sp7XeOtyU9e5TXnMcvak17cjo+A
# 2raRmECQecN4x7axxLVqGDgDEI3Y1DekLgV9iPWCPhCRcKtVgkEy19sEcypukQF8
# IUzUvK4bA3VdeGbZOjFEmjNAvwjXWkmkwuapoGfdpCe8oU85tRFYF/ckXEaPZPfB
# aYh2mHY9WV1CdoeJl2l6SPDgohIbZpp0yt5LHucOY67m1O+SkjqePdwA5EUlibaa
# RBkrfsCUtNJhbesz2cXfSwQAzH0clcOP9yGyshG3u3/y1YxwLEFgqrFjGESVGnZi
# fvaAsPvoZKYz0YkH4b235kOkGLimdwHhD5QMIR2yVCkliWzlDlJRR3S+Jqy2QXXe
# eqxfjT/JvNNBERJb5RBQ6zHFynIWIgnffEx1P2PsIV/EIFFrb7GrhotPwtZFX50g
# /KEexcCPorF+CiaZ9eRpL5gdLfXZqbId5RsCAwEAAaOCATowggE2MA8GA1UdEwEB
# /wQFMAMBAf8wHQYDVR0OBBYEFOzX44LScV1kTN8uZz/nupiuHA9PMB8GA1UdIwQY
# MBaAFEXroq/0ksuCMS1Ri6enIZ3zbcgPMA4GA1UdDwEB/wQEAwIBhjB5BggrBgEF
# BQcBAQRtMGswJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBD
# BggrBgEFBQcwAoY3aHR0cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0
# QXNzdXJlZElEUm9vdENBLmNydDBFBgNVHR8EPjA8MDqgOKA2hjRodHRwOi8vY3Js
# My5kaWdpY2VydC5jb20vRGlnaUNlcnRBc3N1cmVkSURSb290Q0EuY3JsMBEGA1Ud
# IAQKMAgwBgYEVR0gADANBgkqhkiG9w0BAQwFAAOCAQEAcKC/Q1xV5zhfoKN0Gz22
# Ftf3v1cHvZqsoYcs7IVeqRq7IviHGmlUIu2kiHdtvRoU9BNKei8ttzjv9P+Aufih
# 9/Jy3iS8UgPITtAq3votVs/59PesMHqai7Je1M/RQ0SbQyHrlnKhSLSZy51PpwYD
# E3cnRNTnf+hZqPC/Lwum6fI0POz3A8eHqNJMQBk1RmppVLC4oVaO7KTVPeix3P0c
# 2PR3WlxUjG/voVA9/HYJaISfb8rbII01YBwCA8sgsKxYoA5AY8WYIsGyWfVVa88n
# q2x2zm8jLfR+cWojayL/ErhULSd+2DrZ8LaHlv1b0VysGMNNn3O3AamfV6peKOK5
# lDCCBrQwggScoAMCAQICEA3HrFcF/yGZLkBDIgw6SYYwDQYJKoZIhvcNAQELBQAw
# YjELMAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQ
# d3d3LmRpZ2ljZXJ0LmNvbTEhMB8GA1UEAxMYRGlnaUNlcnQgVHJ1c3RlZCBSb290
# IEc0MB4XDTI1MDUwNzAwMDAwMFoXDTM4MDExNDIzNTk1OVowaTELMAkGA1UEBhMC
# VVMxFzAVBgNVBAoTDkRpZ2lDZXJ0LCBJbmMuMUEwPwYDVQQDEzhEaWdpQ2VydCBU
# cnVzdGVkIEc0IFRpbWVTdGFtcGluZyBSU0E0MDk2IFNIQTI1NiAyMDI1IENBMTCC
# AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALR4MdMKmEFyvjxGwBysdduj
# Rmh0tFEXnU2tjQ2UtZmWgyxU7UNqEY81FzJsQqr5G7A6c+Gh/qm8Xi4aPCOo2N8S
# 9SLrC6Kbltqn7SWCWgzbNfiR+2fkHUiljNOqnIVD/gG3SYDEAd4dg2dDGpeZGKe+
# 42DFUF0mR/vtLa4+gKPsYfwEu7EEbkC9+0F2w4QJLVSTEG8yAR2CQWIM1iI5PHg6
# 2IVwxKSpO0XaF9DPfNBKS7Zazch8NF5vp7eaZ2CVNxpqumzTCNSOxm+SAWSuIr21
# Qomb+zzQWKhxKTVVgtmUPAW35xUUFREmDrMxSNlr/NsJyUXzdtFUUt4aS4CEeIY8
# y9IaaGBpPNXKFifinT7zL2gdFpBP9qh8SdLnEut/GcalNeJQ55IuwnKCgs+nrpuQ
# NfVmUB5KlCX3ZA4x5HHKS+rqBvKWxdCyQEEGcbLe1b8Aw4wJkhU1JrPsFfxW1gao
# u30yZ46t4Y9F20HHfIY4/6vHespYMQmUiote8ladjS/nJ0+k6MvqzfpzPDOy5y6g
# qztiT96Fv/9bH7mQyogxG9QEPHrPV6/7umw052AkyiLA6tQbZl1KhBtTasySkuJD
# psZGKdlsjg4u70EwgWbVRSX1Wd4+zoFpp4Ra+MlKM2baoD6x0VR4RjSpWM8o5a6D
# 8bpfm4CLKczsG7ZrIGNTAgMBAAGjggFdMIIBWTASBgNVHRMBAf8ECDAGAQH/AgEA
# MB0GA1UdDgQWBBTvb1NK6eQGfHrK4pBW9i/USezLTjAfBgNVHSMEGDAWgBTs1+OC
# 0nFdZEzfLmc/57qYrhwPTzAOBgNVHQ8BAf8EBAMCAYYwEwYDVR0lBAwwCgYIKwYB
# BQUHAwgwdwYIKwYBBQUHAQEEazBpMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5k
# aWdpY2VydC5jb20wQQYIKwYBBQUHMAKGNWh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0
# LmNvbS9EaWdpQ2VydFRydXN0ZWRSb290RzQuY3J0MEMGA1UdHwQ8MDowOKA2oDSG
# Mmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRydXN0ZWRSb290RzQu
# Y3JsMCAGA1UdIAQZMBcwCAYGZ4EMAQQCMAsGCWCGSAGG/WwHATANBgkqhkiG9w0B
# AQsFAAOCAgEAF877FoAc/gc9EXZxML2+C8i1NKZ/zdCHxYgaMH9Pw5tcBnPw6O6F
# TGNpoV2V4wzSUGvI9NAzaoQk97frPBtIj+ZLzdp+yXdhOP4hCFATuNT+ReOPK0mC
# efSG+tXqGpYZ3essBS3q8nL2UwM+NMvEuBd/2vmdYxDCvwzJv2sRUoKEfJ+nN57m
# QfQXwcAEGCvRR2qKtntujB71WPYAgwPyWLKu6RnaID/B0ba2H3LUiwDRAXx1Neq9
# ydOal95CHfmTnM4I+ZI2rVQfjXQA1WSjjf4J2a7jLzWGNqNX+DF0SQzHU0pTi4dB
# wp9nEC8EAqoxW6q17r0z0noDjs6+BFo+z7bKSBwZXTRNivYuve3L2oiKNqetRHdq
# fMTCW/NmKLJ9M+MtucVGyOxiDf06VXxyKkOirv6o02OoXN4bFzK0vlNMsvhlqgF2
# puE6FndlENSmE+9JGYxOGLS/D284NHNboDGcmWXfwXRy4kbu4QFhOm0xJuF2EZAO
# k5eCkhSxZON3rGlHqhpB/8MluDezooIs8CVnrpHMiD2wL40mm53+/j7tFaxYKIqL
# 0Q4ssd8xHZnIn/7GELH3IdvG2XlM9q7WP/UwgOkw/HQtyRN62JK4S1C8uw3PdBun
# vAZapsiI5YKdvlarEvf8EA+8hcpSM9LHJmyrxaFtoza2zNaQ9k+5t1wwggbtMIIE
# 1aADAgECAhAKgO8YS43xBYLRxHanlXRoMA0GCSqGSIb3DQEBCwUAMGkxCzAJBgNV
# BAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwgSW5jLjFBMD8GA1UEAxM4RGlnaUNl
# cnQgVHJ1c3RlZCBHNCBUaW1lU3RhbXBpbmcgUlNBNDA5NiBTSEEyNTYgMjAyNSBD
# QTEwHhcNMjUwNjA0MDAwMDAwWhcNMzYwOTAzMjM1OTU5WjBjMQswCQYDVQQGEwJV
# UzEXMBUGA1UEChMORGlnaUNlcnQsIEluYy4xOzA5BgNVBAMTMkRpZ2lDZXJ0IFNI
# QTI1NiBSU0E0MDk2IFRpbWVzdGFtcCBSZXNwb25kZXIgMjAyNSAxMIICIjANBgkq
# hkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0EasLRLGntDqrmBWsytXum9R/4ZwCgHf
# yjfMGUIwYzKomd8U1nH7C8Dr0cVMF3BsfAFI54um8+dnxk36+jx0Tb+k+87H9WPx
# NyFPJIDZHhAqlUPt281mHrBbZHqRK71Em3/hCGC5KyyneqiZ7syvFXJ9A72wzHpk
# BaMUNg7MOLxI6E9RaUueHTQKWXymOtRwJXcrcTTPPT2V1D/+cFllESviH8YjoPFv
# ZSjKs3SKO1QNUdFd2adw44wDcKgH+JRJE5Qg0NP3yiSyi5MxgU6cehGHr7zou1zn
# OM8odbkqoK+lJ25LCHBSai25CFyD23DZgPfDrJJJK77epTwMP6eKA0kWa3osAe8f
# cpK40uhktzUd/Yk0xUvhDU6lvJukx7jphx40DQt82yepyekl4i0r8OEps/FNO4ah
# fvAk12hE5FVs9HVVWcO5J4dVmVzix4A77p3awLbr89A90/nWGjXMGn7FQhmSlIUD
# y9Z2hSgctaepZTd0ILIUbWuhKuAeNIeWrzHKYueMJtItnj2Q+aTyLLKLM0MheP/9
# w6CtjuuVHJOVoIJ/DtpJRE7Ce7vMRHoRon4CWIvuiNN1Lk9Y+xZ66lazs2kKFSTn
# nkrT3pXWETTJkhd76CIDBbTRofOsNyEhzZtCGmnQigpFHti58CSmvEyJcAlDVcKa
# cJ+A9/z7eacCAwEAAaOCAZUwggGRMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFOQ7
# /PIx7f391/ORcWMZUEPPYYzoMB8GA1UdIwQYMBaAFO9vU0rp5AZ8esrikFb2L9RJ
# 7MtOMA4GA1UdDwEB/wQEAwIHgDAWBgNVHSUBAf8EDDAKBggrBgEFBQcDCDCBlQYI
# KwYBBQUHAQEEgYgwgYUwJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0
# LmNvbTBdBggrBgEFBQcwAoZRaHR0cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0Rp
# Z2lDZXJ0VHJ1c3RlZEc0VGltZVN0YW1waW5nUlNBNDA5NlNIQTI1NjIwMjVDQTEu
# Y3J0MF8GA1UdHwRYMFYwVKBSoFCGTmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9E
# aWdpQ2VydFRydXN0ZWRHNFRpbWVTdGFtcGluZ1JTQTQwOTZTSEEyNTYyMDI1Q0Ex
# LmNybDAgBgNVHSAEGTAXMAgGBmeBDAEEAjALBglghkgBhv1sBwEwDQYJKoZIhvcN
# AQELBQADggIBAGUqrfEcJwS5rmBB7NEIRJ5jQHIh+OT2Ik/bNYulCrVvhREafBYF
# 0RkP2AGr181o2YWPoSHz9iZEN/FPsLSTwVQWo2H62yGBvg7ouCODwrx6ULj6hYKq
# dT8wv2UV+Kbz/3ImZlJ7YXwBD9R0oU62PtgxOao872bOySCILdBghQ/ZLcdC8cbU
# UO75ZSpbh1oipOhcUT8lD8QAGB9lctZTTOJM3pHfKBAEcxQFoHlt2s9sXoxFizTe
# HihsQyfFg5fxUFEp7W42fNBVN4ueLaceRf9Cq9ec1v5iQMWTFQa0xNqItH3CPFTG
# 7aEQJmmrJTV3Qhtfparz+BW60OiMEgV5GWoBy4RVPRwqxv7Mk0Sy4QHs7v9y69NB
# qycz0BZwhB9WOfOu/CIJnzkQTwtSSpGGhLdjnQ4eBpjtP+XB3pQCtv4E5UCSDag6
# +iX8MmB10nfldPF9SVD7weCC3yXZi/uuhqdwkgVxuiMFzGVFwYbQsiGnoa9F5AaA
# yBjFBtXVLcKtapnMG3VH3EmAp/jsJ3FVF3+d1SVDTmjFjLbNFZUWMXuZyvgLfgyP
# ehwJVxwC+UpX2MSey2ueIu9THFVkT+um1vshETaWyQo8gmBto/m3acaP9QsuLj3F
# NwFlTxq25+T4QwX9xa6ILs84ZPvmpovq90K8eWyG2N01c4IhSOxqt81nMYIE+jCC
# BPYCAQEwLzAbMRkwFwYDVQQDDBBSSFNIT1VSQVYtSVQtT3BzAhAQvylGgaQVhE7g
# tCp7LUPgMAkGBSsOAwIaBQCgeDAYBgorBgEEAYI3AgEMMQowCKACgAChAoAAMBkG
# CSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisGAQQBgjcCAQsxDjAMBgorBgEE
# AYI3AgEVMCMGCSqGSIb3DQEJBDEWBBQKRBpfuye8BMrL2iCHYWwTWHZZLjANBgkq
# hkiG9w0BAQEFAASCAQAcuIoP92OPYHRItSDDWCLF2bGjuh25qlAIUeqDZtzzUBaI
# Qoyei+EqnY6bN0OdkYpWTn+83zMQ/4UOHfn8gYQLPPFBkEnEmxI+e4vRznc6GZuA
# 35TE4eK00wHC9a0NuH4vu0EeyQLfl3kmJpdEeTxHSuOHqZTB6eJSSYPVSoS6G+EU
# bTFSExgGL/SKxc/mj5lwoYXi9Q+zBUgrNxrd4uipFaWs9cxcz8IvytKtxUme9ste
# HpYBopH/SN3DDI/Z/f2y6pgVHMlsr5AhPccbdZm1WEeUKOuB5aGetWv2tGP9op+9
# tT7ZrAt3b2jzSwtK1dJxeLZZyT/nCjoKx4AllUTloYIDJjCCAyIGCSqGSIb3DQEJ
# BjGCAxMwggMPAgEBMH0waTELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDkRpZ2lDZXJ0
# LCBJbmMuMUEwPwYDVQQDEzhEaWdpQ2VydCBUcnVzdGVkIEc0IFRpbWVTdGFtcGlu
# ZyBSU0E0MDk2IFNIQTI1NiAyMDI1IENBMQIQCoDvGEuN8QWC0cR2p5V0aDANBglg
# hkgBZQMEAgEFAKBpMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcN
# AQkFMQ8XDTI2MDcwNzA4NDUwNVowLwYJKoZIhvcNAQkEMSIEILWS1NezmWzhmGhw
# D+gLA5RmE8GYWIZ9+SFTpn3xmqQLMA0GCSqGSIb3DQEBAQUABIICAGPD561mPwn0
# elxz5uWl298OgslZH4gvjzgF8slMIjXkZBDI48lF1ofdTQPyaEVNqa+zOvkHrF9g
# gVgPgtI1BEmlySAkDVTIa9Uh3+fIXR2WxmhEDhAUSXdOhil3uvupXjtEc4lkx3kk
# wrI5kP+2RICfxRUzyt80GS4i+WCHztFq351x+CUNCAZJpQiWazfnl8SrEl8IN3KH
# EVAIqgh+2i3dqV0saQ1KL2Hj4Soum9RLq8nowfr/AR0rKRkDY1lzBgm38zY0w09R
# +Vm3tS/9OBnkaC8W0FgutlicwdlciwDMGXyEM9dbPcDZX/iwrI45SRLBmNaTWb61
# agMmvF227JZdxaBapNDFuoEdbtoztmNtJaDLDe9SOFLWsXmRU58tk0+fasq+1XqO
# eNSGLHt11R8acy4rzxk4i4yrE41GSxskgI4sSJSiac27MVQh/XkdaSeNSUCRIHp8
# Mn6bkalIBc/gcAys3T7zDhOrAJ5Pyudu0h3m49b3hTwbQt+AGJKE2XFfdQdAk83f
# uuMAc9Dfi68AcahWEbElM5vtkRPGzvPGVnqJ4MBeLZNTBLi0qA5mlRdrNawgQsG6
# gYrHopjeLPgz2x7/r+jRSejMScll5Hk2i22bG46iGNe37jByuSkOvjcyPrOzOTr2
# XY/Gv9uAAXOu9bnNBN6oyj/9zqC5l39c
# SIG # End signature block
